name: Build and Push Docker Image

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Docker image tag (e.g., latest, v1.0.0)"
        required: true
        default: "latest"
        type: string

env:
  DOCKER_IMAGE: unstealable/vrchatbridge

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.DOCKER_IMAGE }}:${{ github.event.inputs.tag }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Success notification
        run: |
          echo "✅ Docker image pushed successfully!"
          echo "Image: ${{ env.DOCKER_IMAGE }}:${{ github.event.inputs.tag }}"
          echo "Docker Hub: https://hub.docker.com/r/${{ env.DOCKER_IMAGE }}"
